# =========================================================================
# FRAMEWORK SCRIPT POWERSHELL DENGAN EKSPOR OTOMATIS (V2.6)
# Nama Skrip: Bulk-EntraPasswordReset-AutoGenerate
# Deskripsi: Reset password massal dengan password acak yang dibuat sistem.
# =========================================================================

# 1. Konfigurasi File Input & Path
$inputFileName = "UserPrincipalName.csv"
$scriptDir = if ($PSScriptRoot) { $PSScriptRoot } else { (Get-Location).Path }
$inputFilePath = Join-Path -Path $scriptDir -ChildPath $inputFileName

# Variabel Global dan Output
$scriptName = "BulkAutoPasswordReset" 
$scriptOutput = [System.Collections.ArrayList]::new() 
$timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
$outputFileName = "Output_$($scriptName)_$($timestamp).csv"
$outputFilePath = Join-Path -Path $scriptDir -ChildPath $outputFileName

## -----------------------------------------------------------------------
## 1. PRASYARAT DAN INSTALASI MODUL
## -----------------------------------------------------------------------

Write-Host "--- 1. Memeriksa Lingkungan PowerShell ---" -ForegroundColor Blue

function CheckAndInstallModule {
    param([string]$ModuleName)
    Write-Host "1.$(++$global:moduleStep). Memeriksa Modul '$ModuleName'..." -ForegroundColor Cyan
    if (!(Get-Module -Name $ModuleName -ListAvailable)) {
        Install-Module -Name $ModuleName -Force -AllowClobber -Scope CurrentUser -ErrorAction Stop
    }
}

$global:moduleStep = 1
CheckAndInstallModule -ModuleName "Microsoft.Entra"

## -----------------------------------------------------------------------
## 2. FUNGSI GENERATOR PASSWORD & KONEKSI
## -----------------------------------------------------------------------

# Fungsi untuk membuat password acak 12 karakter yang aman
function Generate-RandomPassword {
    $length = 12
    $chars = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%^&*"
    $randomPassword = ""
    for ($i = 0; $i -lt $length; $i++) {
        $randomPassword += $chars[(Get-Random -Minimum 0 -Maximum $chars.Length)]
    }
    return $randomPassword
}

Write-Host "`n--- 2. Membangun Koneksi ke Microsoft Entra ---" -ForegroundColor Blue

try {
    Write-Host "Menghubungkan ke Microsoft Entra..." -ForegroundColor Yellow
    Connect-Entra -Scopes 'User.ReadWrite.All' -ErrorAction Stop
    Write-Host "Koneksi Berhasil." -ForegroundColor Green
} catch {
    Write-Error "Gagal terhubung: $($_.Exception.Message)"
    exit 1
}

## -----------------------------------------------------------------------
## 3. LOGIKA UTAMA SCRIPT
## -----------------------------------------------------------------------

Write-Host "`n--- 3. Memulai Proses Reset Password Otomatis ---" -ForegroundColor Magenta

if (Test-Path $inputFilePath) {
    # Import CSV (Asumsi: File hanya berisi daftar email tanpa header)
    $users = Import-Csv $inputFilePath -Header "TempColumn" | Where-Object { $_.TempColumn -ne $null -and $_.TempColumn.Trim() -ne "" }
    $totalUsers = $users.Count
    $counter = 0

    foreach ($user in $users) {
        $counter++
        $targetUser = $user.TempColumn.Trim()
        
        # Buat Password Baru secara acak untuk user ini
        $autoGeneratedPassword = Generate-RandomPassword
        
        # Tampilan progres baris tunggal
        $statusText = "-> [$counter/$totalUsers] Memproses: $targetUser . . ."
        Write-Host "`r$statusText" -ForegroundColor Green -NoNewline

        try {
            # Eksekusi Reset Password
            Set-EntraUser -UserId $targetUser -PasswordProfile @{
                Password = $autoGeneratedPassword
                ForceChangePasswordNextSignIn = $true
            } -ErrorAction Stop

            $res = [PSCustomObject]@{
                Timestamp         = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
                UserPrincipalName = $targetUser
                TemporaryPassword = $autoGeneratedPassword # Simpan password di log CSV
                Status            = "SUCCESS"
                Message           = "Password auto-generated and reset"
            }
        } catch {
            $res = [PSCustomObject]@{
                Timestamp         = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
                UserPrincipalName = $targetUser
                TemporaryPassword = "-"
                Status            = "FAILED"
                Message           = $_.Exception.Message
            }
        }
        [void]$scriptOutput.Add($res)
    }
    Write-Host "`n`nPemrosesan Selesai." -ForegroundColor Green
} else {
    Write-Host "ERROR: File '$inputFileName' tidak ditemukan!" -ForegroundColor Red
}

## -----------------------------------------------------------------------
## 4. CLEANUP DAN EKSPOR HASIL
## -----------------------------------------------------------------------

Write-Host "`n--- 4. Cleanup dan Ekspor Hasil ---" -ForegroundColor Blue

if ($scriptOutput.Count -gt 0) {
    # Hasil ekspor akan berisi daftar password baru untuk dibagikan ke user
    $scriptOutput | Export-Csv -Path $outputFilePath -NoTypeInformation -Delimiter ";" -Encoding UTF8
    Write-Host " Laporan detail dan daftar password baru tersimpan di:" -ForegroundColor Green
    Write-Host " $outputFilePath" -ForegroundColor Cyan
}

Disconnect-Entra -ErrorAction SilentlyContinue
Write-Host "`nSkrip selesai dieksekusi." -ForegroundColor Yellow